Fe summary
jhupprevature/rev-TutorMS pull request #56
Opened 2021-08-15 22:18 UTC by jhupprevature

2021-08-15 22:24 UTC, DeyondreBeale requested changes
Does your code run? You commented out a lot of things. Ill try pushing what I have first then you can make changes to your pull request.

2021-08-15 22:38 UTC, caocmai commented
I can't run this code also.

2021-08-16 05:28 UTC, jhupprevature commented
assigned changes were fixed.
analytics page is up and running.
course demand feature is populating incorrectly, this is a back end problem. (I will look into it.)

2021-08-16 05:47 UTC, DeyondreBeale approved these changes

2021-08-16 05:51 UTC, merged